#!/sbin/openrc-run
# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# shellcheck shell=sh disable=SC2034

description="Configures network interfaces"

depend() {
	need sysfs localmount
	after bootmisc modules
	provide net
}

start() {
	ebegin "Starting ifstate"
	ifstatecli --quiet apply
	eend $?
}

stop() {
	ebegin "Stopping ifstate"
	eend 0
}
